export const ADD_NUMBER = 'ADD_NUMBER';
export const ADD_GAME_MOVE = 'ADD_GAME_MOVE';
export const JUMP_TO_GAME_HISTORY = 'JUMP_TO_GAME_HISTORY';
export const EXAMPLE_FETCH_REQUESTED = 'EXAMPLE_FETCH_REQUESTED';
